# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96e04f10ba251855110e45352fbf06fe7b511f51758ab457c627d579cb00054f23fb8b1e3235453a721b356b01791cda0382df41c2f4a00d9757bb1ed318f27c

test:
  secret_key_base: 47c44ab42dbaa32670da57db99e976f82fb7f96d38f6a135ca52617955f3800c2cb39d79e7777f626a06a10eb006b108685d2c6dfa594d18b694bf46f3729c74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
